### ISSUE TITLE
ACTIVIDAD 1 MAPA MENTAL

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-1-mapa-mental-YaelTrinidad#1]
[mapa.mental.inv.doc.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-YaelTrinidad/files/9465348/mapa.mental.inv.doc.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica has obtenido un 19.4% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
